version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  server:
    profiles: ["server"]
    build:
        context: .
        dockerfile: Dockerfile
    image: kafka-app
    container_name: kafka-server
    environment:
      KAFKA_BROKERS: kafka:9092
      TARGET: producer
    depends_on:
      - kafka

  client:
    profiles: ["client"]
    image: kafka-app
    container_name: kafka-client
    environment:
      KAFKA_BROKERS: kafka:9092
      TARGET: consumer
